### ISSUE TITLE
Spawn model tool doesn't use outline of model

### ISSUE THREAD

**Issue by josephduchesne** [avidbots/flatland#15]
Currently the spawn model tool uses a static 3d model that doesn't match the model to preview the shape being placed. It should either use a more generic shape (an arrow etc.) or parse the model yaml to generate a footprint shape dynamically.

**Comment by mbrousse** [comment]
http://www.ogre3d.org/tikiwiki/ManualObject might be the quickest way

**Comment by mbrousse** [comment]
Sorry I should not have closed this one, still learning

**Comment by josephduchesne** [comment]
Hi Mike,
I don't have your personal email. I just noticed that your contributions aren't showing up under your account on the contributors list ( https://github.com/avidbots/flatland/graphs/contributors ). This isn't intentional, but is because your commits are under your Avidbots email rather than the email that's linked to your github account. 

If you'd like to fix that, send me your github email and I'll revise the git history so that your contributions are correctly labelled and associated with your github account.

**Comment by mbrousse** [comment]
Thanks, I would appreciate that.

The email I used for gitHub is mike.brousseau.13@gmail.com.

I no longer have the mbrousse@rogers.com anymore as we switched to bell.

I now use my gmail above as my primary email address.

Thanks again
Mike
