### ISSUE TITLE
Support optional prefix for topics and namespaces to aid in multi-robot support

### ISSUE THREAD

**Issue by josephduchesne** [avidbots/flatland#17]
* TF should string-prefix the prefix ("base" with prefix "foo" becomes "foo-base").
* Topics should use prefix as namespace ( "cmd_vel" becomes "foo/cmd_vel"

The flatland API should provide functions to prefix topics and tfs so that all plugins can use this consistently.

Prefixes should default to "", which should not do anything to the string (no "-" or "/" prefix added).

**Comment by mbrousse** [comment]
Be sure testing includes the "." as I noticed some intermittent problems loading models with "." in the filename.

**Comment by josephduchesne** [comment]
Done in #19
