### ISSUE TITLE
Would a local frame TwistStamped output be helpful?

### ISSUE THREAD

**Issue by robustify** [avidbots/flatland#40]
In my class, I show my students how to apply dead reckoning to encoder measurements to generate odometry outputs for use by SLAM or AMCL.  To demonstrate this, I plan on modifying the diff_drive plugin to optionally output a local frame TwistStamped message to simulate encoder-derived speed and yaw rate measurements.

I realize this is a pretty specific use case, since the existing odometry output almost produces what I make the students do themselves. The only difference is that by integrating a noisy local frame twist, drift will accumulate over time. If you foresee this feature being useful for your purposes though, I can make a pull request about this for you to review.

**Comment by josephduchesne** [comment]
That sounds quite useful!
