### ISSUE TITLE
Disable Collision?

### ISSUE THREAD

**Issue by RGring** [avidbots/flatland#52]
Is it possible to disable the physics like in gazebo? I don't need it and hope to speed up the simulation like that.

**Comment by josephduchesne** [comment]
I'm not sure physics update is a big part of the loop time but I'm going to profile it with and without m_continuousPhysics enabled in box2d to see if it's worth adding an option.

You should be able to set the position_iterations and velocity_iterations in world settings (or via node settings) Setting position iterations to 0 might also work.

In most cases flatland doesn't do much physics wise unless you have a large number of models. From memory the biggest CPU load is typically the laser scan plugin. That can be speed up by reducing the angular resolution or frequency.

See https://flatland-simulator.readthedocs.io/en/latest/core_functions/world.html

**Comment by RGring** [comment]
Thanks for the fast reply!
I might have formulated the issue wrong.  I actually just don't need the collision part.
I want to model a dynamic crowd of people. Means, people can walk through each other.

**Comment by josephduchesne** [comment]
I've added a property model body footprints "collision", default true. Set it to "false" and they won't collide with anything in PR #54

If you need the ability to set collision between specific groups, let me know and I can work on that later. It's not that hard, but I thought this was a good start.

**Comment by RGring** [comment]
Oh thanks a lot. I will try it out tomorrow!
Collisions between specific groups I don't need.

**Comment by josephduchesne** [comment]
Feel free to reopen this if you have any more related questions.
